#! /bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=marcomanager
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/opt/marcomanager/marcomanager.py
DAEMON_OPTS="8000"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
. /lib/lsb/init-functions
case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
        start-stop-daemon --make-pidfile --background --start --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        start-stop-daemon --stop --oknodo --pidfile $PIDFILE
        echo "."
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        start-stop-daemon --stop  --oknodo --retry 30 --pidfile
$PIDFILE
        start-stop-daemon --make-pidfile --background --start --
pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
        ;;
  reload)
	echo -n "Reloading daemon: "$NAME
	start-stop-daemon --stop --signal 10 --quiet --pidfile $PIDFILE --name $NAME
	echo "."
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?	
	;;
  *)
        echo "Usage: "$1" {start|stop|reload|restart}"
        exit 1
esac

exit 0
